apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-spring
  namespace: was
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: backend
        image: hashicorp/http-echo:latest
        args:
          - "-text=<h1>WAS Backend Tier</h1><p>Service Status: Operational</p><p>Environment: Production</p>"
          - "-listen=:8080"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
