apiVersion: v1
kind: Namespace
metadata:
  name: petclinic

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: petclinic
data:
  default.conf: |
    upstream backend {
        server petclinic-was-service:8080;
    }
    
    server {
        listen 80;
        server_name _;
        
        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-was
  namespace: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
      tier: was
  template:
    metadata:
      labels:
        app: petclinic
        tier: was
    spec:
      containers:
      - name: spring-boot
        image: springcommunity/spring-petclinic:3.3.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: petclinic-config
        - secretRef:
            name: petclinic-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-was-service
  namespace: petclinic
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: petclinic
    tier: was

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-web
  namespace: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
      tier: web
  template:
    metadata:
      labels:
        app: petclinic
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-web-service
  namespace: petclinic
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: petclinic
    tier: web
